server:
  port: 9080
  
spring:
  application:
    name: msa-auth-server
    
  data:
    mongodb:
      host: mongodb-standalone-0.mongodb
      username: user
      password: password
      database: sample01
      port: 27017

#Eureka Client   
eureka:
  instance:
    prefer-ip-address: true         #HostName이 IP 에 의존하여 설정
  client:
    registerWithEureka: true       #자체 서비스를 eureka 서버에 등록 할지 여부
    fetchRegistry: true            #client 서비스가 eureka 서버로 부터 서비스 리스트 정보를 local에 caching 할지 여부
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://msa-eureka-server:8761/eureka/

signing.key: "345345fsdgsf5345"