server:
  port: 8888
  
spring:
  application:
    name: msa-config-server

#git repository trigger config      
  cloud:
    config:
      server:
        git: 
          uri: "https://github.com/Sokju/msa_sample01"
          search-paths: platform_config
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
#  profiles:
#     active: native

#Eureka Client   
eureka:
  instance:
    prefer-ip-address: true         #HostName이 IP 에 의존하여 설정
  client:
    registerWithEureka: true       #자체 서비스를 eureka 서버에 등록 할지 여부
    fetchRegistry: true            #client 서비스가 eureka 서버로 부터 서비스 리스트 정보를 local에 caching 할지 여부
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://msa-eureka-server:8761/eureka/      